default: &default
  pool: 5
  timeout: 5000

development:
 <<: *default
 adapter: postgresql
 encoding: unicode
 host: localhost
 # username: furqan
 # password: root
 database: sample_rails_development

test:
  <<: *default
  adapter: postgresql
  host: localhost
  # username: furqan
  # password: root
  database: sample_rails_test


#test:
#  <<: *default
#  adapter: postgresql
#  encoding: unicode
#  host: db
#  username: postgres
#  password:
#  database: sample_rails_app_db_test

production:
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: sample_app_production
  username: sample_app
  password: <%= ENV['SAMPLE_APP_DATABASE_PASSWORD'] %>